<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from com.skvare.ultracampsync/xml/schema/CRM/Ultracampsync/Ultracamp.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:5e52662ce7b0dea3268eff4c001eb39d)
 */
use CRM_Ultracampsync_ExtensionUtil as E;

/**
 * Database access object for the Ultracamp entity.
 */
class CRM_Ultracampsync_DAO_Ultracamp extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_ultracamp';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = FALSE;

  /**
   * Unique Ultracamp ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * ReservationId
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $reservation_id;

  /**
   * FK to Contact
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $contact_id;

  /**
   * Account ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $account_id;

  /**
   * Person ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $person_id;

  /**
   * Session ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $session_id;

  /**
   * @var string
   *   (SQL type: varchar(512))
   *   Note that values will be retrieved from the database as a string.
   */
  public $session_name;

  /**
   * @var string|null
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $order_date;

  /**
   * @var string
   *   (SQL type: varchar(100))
   *   Note that values will be retrieved from the database as a string.
   */
  public $status;

  /**
   * @var string
   *   (SQL type: varchar(1024))
   *   Note that values will be retrieved from the database as a string.
   */
  public $message;

  /**
   * Data.
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $data;

  /**
   * FK to Contact
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $manual_contact_id;

  /**
   * FK to Participant
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $participant_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_ultracamp';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Ultracamps') : E::ts('Ultracamp');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique Ultracamp ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_ultracamp.id',
          'table_name' => 'civicrm_ultracamp',
          'entity' => 'Ultracamp',
          'bao' => 'CRM_Ultracampsync_DAO_Ultracamp',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'reservation_id' => [
          'name' => 'reservation_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Reservation ID'),
          'description' => E::ts('ReservationId'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_ultracamp.reservation_id',
          'table_name' => 'civicrm_ultracamp',
          'entity' => 'Ultracamp',
          'bao' => 'CRM_Ultracampsync_DAO_Ultracamp',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Contact ID'),
          'description' => E::ts('FK to Contact'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_ultracamp.contact_id',
          'table_name' => 'civicrm_ultracamp',
          'entity' => 'Ultracamp',
          'bao' => 'CRM_Ultracampsync_DAO_Ultracamp',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'html' => [
            'type' => 'EntityRef',
            'label' => E::ts("Contact"),
          ],
          'add' => NULL,
        ],
        'account_id' => [
          'name' => 'account_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Account ID'),
          'description' => E::ts('Account ID'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_ultracamp.account_id',
          'table_name' => 'civicrm_ultracamp',
          'entity' => 'Ultracamp',
          'bao' => 'CRM_Ultracampsync_DAO_Ultracamp',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'person_id' => [
          'name' => 'person_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Person ID'),
          'description' => E::ts('Person ID'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_ultracamp.person_id',
          'table_name' => 'civicrm_ultracamp',
          'entity' => 'Ultracamp',
          'bao' => 'CRM_Ultracampsync_DAO_Ultracamp',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'session_id' => [
          'name' => 'session_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Session ID'),
          'description' => E::ts('Session ID'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_ultracamp.session_id',
          'table_name' => 'civicrm_ultracamp',
          'entity' => 'Ultracamp',
          'bao' => 'CRM_Ultracampsync_DAO_Ultracamp',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'session_name' => [
          'name' => 'session_name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Session Name'),
          'required' => FALSE,
          'maxlength' => 512,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_ultracamp.session_name',
          'export' => TRUE,
          'table_name' => 'civicrm_ultracamp',
          'entity' => 'Ultracamp',
          'bao' => 'CRM_Ultracampsync_DAO_Ultracamp',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '5.63',
        ],
        'order_date' => [
          'name' => 'order_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Order Date'),
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_ultracamp.order_date',
          'headerPattern' => '/replace(.?date)?/i',
          'dataPattern' => '/^\d{4}-?\d{2}-?\d{2} ?(\d{2}:?\d{2}:?(\d{2})?)?$/',
          'export' => TRUE,
          'table_name' => 'civicrm_ultracamp',
          'entity' => 'Ultracamp',
          'bao' => 'CRM_Ultracampsync_DAO_Ultracamp',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
          ],
          'add' => NULL,
        ],
        'status' => [
          'name' => 'status',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Processing status'),
          'required' => FALSE,
          'maxlength' => 100,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_ultracamp.status',
          'export' => TRUE,
          'table_name' => 'civicrm_ultracamp',
          'entity' => 'Ultracamp',
          'bao' => 'CRM_Ultracampsync_DAO_Ultracamp',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'callback' => 'CRM_Ultracampsync_Utils::recordStatus',
          ],
          'add' => '5.63',
        ],
        'message' => [
          'name' => 'message',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Message'),
          'required' => FALSE,
          'maxlength' => 1024,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_ultracamp.message',
          'export' => TRUE,
          'table_name' => 'civicrm_ultracamp',
          'entity' => 'Ultracamp',
          'bao' => 'CRM_Ultracampsync_DAO_Ultracamp',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '5.63',
        ],
        'data' => [
          'name' => 'data',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Data'),
          'description' => E::ts('Data.'),
          'rows' => 4,
          'cols' => 60,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_ultracamp.data',
          'export' => TRUE,
          'table_name' => 'civicrm_ultracamp',
          'entity' => 'Ultracamp',
          'bao' => 'CRM_Ultracampsync_DAO_Ultracamp',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
          'add' => '5.63',
        ],
        'manual_contact_id' => [
          'name' => 'manual_contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Manually Assigned Contact ID'),
          'description' => E::ts('FK to Contact'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_ultracamp.manual_contact_id',
          'table_name' => 'civicrm_ultracamp',
          'entity' => 'Ultracamp',
          'bao' => 'CRM_Ultracampsync_DAO_Ultracamp',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'html' => [
            'type' => 'EntityRef',
            'label' => E::ts("Manually Assigned Contact"),
          ],
          'add' => NULL,
        ],
        'participant_id' => [
          'name' => 'participant_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Participant ID'),
          'description' => E::ts('FK to Participant'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_ultracamp.participant_id',
          'table_name' => 'civicrm_ultracamp',
          'entity' => 'Ultracamp',
          'bao' => 'CRM_Ultracampsync_DAO_Ultracamp',
          'localizable' => 0,
          'FKClassName' => 'CRM_Event_DAO_Participant',
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'ultracamp', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'ultracamp', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'index_person_id' => [
        'name' => 'index_person_id',
        'field' => [
          0 => 'person_id',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_ultracamp::0::person_id',
      ],
      'index_session_name' => [
        'name' => 'index_session_name',
        'field' => [
          0 => 'session_name',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_ultracamp::0::session_name',
      ],
      'index_order_date' => [
        'name' => 'index_order_date',
        'field' => [
          0 => 'order_date',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_ultracamp::0::order_date',
      ],
      'index_status' => [
        'name' => 'index_status',
        'field' => [
          0 => 'status',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_ultracamp::0::status',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
