-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from file:drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_ultracamp`;

SET FOREIGN_KEY_CHECKS=1;

-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_ultracamp
-- *
-- * Ultracamp table
-- *
-- *******************************************************/
CREATE TABLE `civicrm_ultracamp` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Ultracamp ID',
  `reservation_id` int unsigned COMMENT 'ReservationId',
  `contact_id` int unsigned COMMENT 'FK to Contact',
  `account_id` int unsigned COMMENT 'Account ID',
  `person_id` int unsigned COMMENT 'Person ID',
  `session_id` int unsigned COMMENT 'Session ID',
  `session_name` varchar(512) NULL,
  `order_date` datetime,
  `status` varchar(100) NULL,
  `message` varchar(1024) NULL,
  `data` text COMMENT 'Data.',
  `manual_contact_id` int unsigned COMMENT 'FK to Contact',
  `participant_id` int unsigned COMMENT 'FK to Participant',
  PRIMARY KEY (`id`),
  INDEX `index_person_id`(person_id),
  INDEX `index_session_name`(session_name),
  INDEX `index_order_date`(order_date),
  INDEX `index_status`(status),
  CONSTRAINT FK_civicrm_ultracamp_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_ultracamp_manual_contact_id FOREIGN KEY (`manual_contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE SET NULL,
  CONSTRAINT FK_civicrm_ultracamp_participant_id FOREIGN KEY (`participant_id`) REFERENCES `civicrm_participant`(`id`) ON DELETE SET NULL)
ENGINE=InnoDB;
